var ALIASES = {};
ALIASES["airb"] = {};
ALIASES["artichoke"] = {};
ALIASES["artichoke_backend"] = {};
ALIASES["artichoke_core"] = {};
ALIASES["artichoke_frontend"] = {};
ALIASES["artichoke_vfs"] = {};
ALIASES["ruby"] = {};
ALIASES["spec_runner"] = {};
